# -*- coding: utf-8 -*-
"""api_interaction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G31LMkeDLCST1EjDas9bmzIuhqJJFarG
"""

import requests

def api_call(api_endpoint, request_dict):

  response = requests.post(api_endpoint, request_dict, apikey)

  return response