# -*- coding: utf-8 -*-
"""event

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BK7zuWsIcDSqt2vf73xUj-oAXrpkd5AD
"""

from datetime import date

class Event:

  def __init__(self, name, date):
    self.name_event = name
    self.date_event = date

  def days_until_event(self):

    today = date.today()
    return (self.date_event - today).days